"""Main results tables for the write-up, generated from the evaluation CSVs (never typed by hand).

    .venv/bin/python scripts/main_tables.py      -> results/tables/main_results.md

TUM: ATE [m] (first segment, Umeyama) averaged over the 5 sequences every method finishes, finished sequences,
failures per run, keyframe rate, SVO time per frame. Multi-seed methods: mean +- std over seeds (3 repeats each).
TartanAir: finished trajectories and failures per trajectory on the fixed core set (6) and, where available, on all
13 held-out trajectories (incl. Hard).
"""
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
E = ROOT / "results" / "eval"
COMMON = ["desk", "desk2", "plant", "teddy", "xyz"]
PAPER = {"Paper: SVO": {"desk": 0.681, "desk2": 0.898, "plant": 0.320, "teddy": 0.769, "xyz": 0.057},
         "Paper: RL-SVO": {"desk": 0.556, "desk2": 0.755, "plant": 0.260, "teddy": 0.697, "xyz": 0.062}}

# (label, TUM csvs per seed, TartanAir core csvs, TartanAir all-13 csvs, training data)
METHODS = [
    ("SVO rules (tuned)", ["tum/svo_rules_std/heuristic.csv"], ["tartanair/bc/heuristic.csv"],
     ["tartanair/v2_valall/heuristic.csv"], "-"),
    ("PPO, authors' setup", [f"tum/reward1/reward1_baseline_s{s}.csv" for s in range(3)],
     [f"tartanair/reward1/reward1_baseline_s{s}.csv" for s in range(3)], [], "3 scenes"),
    ("PPO + 20-frame reward window", [f"tum/reward1/reward1_long_window_s{s}.csv" for s in range(3)],
     [f"tartanair/reward1/reward1_long_window_s{s}.csv" for s in range(3)], [], "3 scenes"),
    ("Behavior cloning of the rules", ["tum/bc/bc_rules_s0.csv"], ["tartanair/bc/bc_rules_s0.csv"], [], "3 scenes"),
    ("BC -> PPO", [f"tum/bc/bc_ppo_s{s}.csv" for s in range(3)], [f"tartanair/bc/bc_ppo_s{s}.csv" for s in range(3)],
     [], "3 scenes"),
    ("Residual RL over the rules", [f"tum/residual/residual_s{s}.csv" for s in range(3)],
     [f"tartanair/residual/residual_s{s}.csv" for s in range(3)], [], "3 scenes"),
    ("Constrained PPO (kf rate 0.30)", [f"tum/constrained/constrained_lw_s{s}.csv" for s in range(3)],
     [f"tartanair/constrained/constrained_lw_s{s}.csv" for s in range(3)], [], "3 scenes"),
    ("PPO, authors' setup", ["tum/v2/ppo_v2_s0.csv"], ["tartanair/v2/ppo_v2_s0.csv"],
     ["tartanair/v2_valall/ppo_v2_s0.csv"], "7 scenes"),
    ("BC -> PPO", ["tum/v2/bc_ppo_v2_s0.csv"], ["tartanair/v2/bc_ppo_v2_s0.csv"],
     ["tartanair/v2_valall/bc_ppo_v2_s0.csv"], "7 scenes"),
    ("Constrained PPO (kf rate 0.30)", ["tum/v2/constrained_v2_s0.csv"], ["tartanair/v2/constrained_v2_s0.csv"],
     ["tartanair/v2_valall/constrained_v2_s0.csv"], "7 scenes"),
    ("Shadow-relative reward (sampled)", ["tum/v2_stoch/shadow_rel_v2_s0.csv"], [], [], "7 scenes"),
    ("Shadow-relative reward", ["tum/v2/shadow_rel_v2_s0.csv"], ["tartanair/v2/shadow_rel_v2_s0.csv"],
     ["tartanair/v2_valall/shadow_rel_v2_s0.csv"], "7 scenes"),
]


def per_seq(path, strip="rgbd_dataset_freiburg1_"):
    d = pd.read_csv(E / path)
    d["seq"] = d["trajectory"].str.replace(strip, "")
    return d.groupby("seq").agg(ate=("ate", "mean"), fin=("failures", lambda x: (x == 0).all()),
                                fails=("failures", "mean"), kf=("keyframe_rate", "mean"), ms=("ms_per_step", "mean"))


def fmt(vals, digits=3):
    vals = [v for v in vals if v == v]
    if not vals:
        return "-"
    m = np.mean(vals)
    return f"{m:.{digits}f}" + (f" ± {np.std(vals, ddof=1):.{digits}f}" if len(vals) > 1 else "")


def tartan(paths):
    if not paths:
        return "-", "-"
    gs = [per_seq(p, strip="") for p in paths if (E / p).exists()]
    if not gs:
        return "-", "-"
    n = len(gs[0])
    return fmt([g.fin.sum() for g in gs], 1) + f" / {n}", fmt([g.fails.mean() for g in gs], 2)


def main():
    rules = per_seq(METHODS[0][1][0])
    ref = np.mean([rules.loc[q, "ate"] for q in COMMON])
    lines = ["# Main results (generated by scripts/main_tables.py — do not edit by hand)\n",
             f"TUM-RGBD: ATE [m] averaged over {', '.join(COMMON)} (the sequences every method finishes); same tuned "
             "SVO settings for all methods; 3 evaluation repeats per policy; multi-seed rows are mean ± std over "
             "seeds. 'vs rules' is relative to SVO's tuned rules. TartanAir: held-out trajectories; core = the fixed "
             "6 used throughout, all = 13 incl. Hard.\n",
             "| Method | Train data | Seeds | TUM ATE [m] | vs rules | TUM finished /9 | TUM failures/run | "
             "Keyframe rate | ms/frame | TartanAir core finished | core failures/traj | TartanAir all finished | "
             "all failures/traj |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for name, vals in PAPER.items():
        a = np.mean([vals[q] for q in COMMON])
        lines.append(f"| {name} | full TartanAir | ? | {a:.3f} | {100 * (a / ref - 1):+.0f}%* | 8 (paper) | - | - | - | - | - | - | - |")
    for name, tum, core, allv, data in METHODS:
        gs = [per_seq(p) for p in tum if (E / p).exists()]
        if not gs:
            continue
        ates = [np.mean([g.loc[q, "ate"] for q in COMMON]) for g in gs]
        rel = 100 * (np.mean(ates) / ref - 1)
        cf, cfl = tartan(core)
        af, afl = tartan(allv)
        lines.append(
            f"| {name} | {data} | {len(gs)} | {fmt(ates)} | {rel:+.1f}% | {fmt([g.fin.sum() for g in gs], 1)} | "
            f"{fmt([g.fails.sum() for g in gs], 1)} | {fmt([g.kf.mean() for g in gs], 2)} | "
            f"{fmt([g.ms.mean() for g in gs], 2)} | {cf} | {cfl} | {af} | {afl} |")
    lines.append("\n*Paper rows are relative to OUR tuned SVO rules (the paper's own SVO baseline is 0.545 on these "
                 "sequences; their RL-SVO is -14.5% vs their SVO).")
    out = ROOT / "results" / "tables" / "main_results.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
