"""Training trends from the intermediate policy snapshots (scripts/eval_snapshots.sh), without new training.

    .venv/bin/python scripts/snapshot_trends.py
    -> results/tables/snapshot_trends.md, results/figures/snapshot_trends.png

Every point is evaluation repeat 0 (seed 0), deterministic actions. The final point of each run is repeat 0 of its
regular evaluation CSV (3 repeats were run there). Steps = PPO iteration x n_steps x n_envs (250 x 12 = 3000).
TUM: ATE averaged over the 5 commonly finished sequences, finished sequences /9, failures per run, keyframe rate.
TartanAir: the fixed core set (6 trajectories): finished and failures per trajectory.
"""
import re
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd
from omegaconf import OmegaConf

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
E = ROOT / "results" / "eval"
COMMON = ["desk", "desk2", "plant", "teddy", "xyz"]
# method label -> runs; final-evaluation folder per dataset
METHODS = {
    "PPO, authors' setup (1.5M steps)": (["ppo15_s0"], {"tum": "ppo15_1p5M", "tartanair": "snapshots/final"}),
    "PPO, authors' setup (3 seeds)": ([f"ppo_snap_s{s}" for s in range(3)], {"tum": "ppo_snap", "tartanair": "ppo_snap"}),
    "BC -> PPO": ([f"bc_ppo_s{s}" for s in range(3)], {"tum": "bc", "tartanair": "bc"}),
    "Residual RL": ([f"residual_s{s}" for s in range(3)], {"tum": "residual", "tartanair": "residual"}),
    "Constrained PPO": ([f"constrained_lw_s{s}" for s in range(3)], {"tum": "constrained", "tartanair": "constrained"}),
    "BC -> constrained PPO": (["bc_constrained_lw_s0"], {"tum": "constrained", "tartanair": "constrained"}),
    "PPO (7 scenes)": (["ppo_v2_s0"], {"tum": "v2", "tartanair": "v2"}),
    "BC -> PPO (7 scenes)": (["bc_ppo_v2_s0"], {"tum": "v2", "tartanair": "v2"}),
    "Constrained PPO (7 scenes)": (["constrained_v2_s0"], {"tum": "v2", "tartanair": "v2"}),
    "Shadow-relative reward (7 scenes)": (["shadow_rel_v2_s0"], {"tum": "v2", "tartanair": "v2"}),
}


def summarize(path, ds):
    d = pd.read_csv(path)
    d = d[d["repeat"] == 0]
    if ds == "tum":
        d["seq"] = d["trajectory"].str.replace("rgbd_dataset_freiburg1_", "")
        d = d.set_index("seq")
        return dict(tum_ate=float(np.mean([d.loc[q, "ate"] for q in COMMON])),
                    tum_fin=int((d["failures"] == 0).sum()), tum_fails=float(d["failures"].sum()),
                    tum_kf=float(d["keyframe_rate"].mean()))
    return dict(tar_fin=int((d["failures"] == 0).sum()), tar_fails=float(d["failures"].mean()),
                tar_kf=float(d["keyframe_rate"].mean()))


def points(run, finals):
    cfg = OmegaConf.load(ROOT / "runs" / run / "config.yaml")
    per_iter = cfg.agent.n_steps * cfg.n_envs
    pts = {}
    for ds in ("tum", "tartanair"):
        for p in sorted((E / ds / "snapshots").glob(f"iter_*/{run}.csv")):
            steps = int(re.search(r"iter_(\d+)", p.parent.name).group(1)) * per_iter
            pts.setdefault(steps, {}).update(summarize(p, ds))
        f = E / ds / finals[ds] / f"{run}.csv"
        if f.exists():
            pts.setdefault(int(cfg.total_timesteps), {}).update(summarize(f, ds))
    return pd.DataFrame([dict(steps=s, **v) for s, v in sorted(pts.items())])


def main():
    rows, curves = [], {}
    for label, (runs, finals) in METHODS.items():
        dfs = [points(r, finals) for r in runs if (ROOT / "runs" / r).exists()]
        if not dfs:
            continue
        df = pd.concat(dfs).groupby("steps").mean(numeric_only=True).reset_index()   # mean over seeds
        curves[label] = df
        for _, r in df.iterrows():
            rows.append({"method": label, "seeds": len(dfs), "steps [k]": int(r.steps / 1000),
                         **{k: r.get(k, np.nan) for k in
                            ["tum_ate", "tum_fin", "tum_fails", "tum_kf", "tar_fin", "tar_fails", "tar_kf"]}})
    t = pd.DataFrame(rows)
    rules_tum = pd.read_csv(E / "tum/svo_rules_std/heuristic.csv")
    rules = summarize(E / "tum/svo_rules_std/heuristic.csv", "tum") if len(rules_tum) else {}
    rules_tar = summarize(E / "tartanair/bc/heuristic.csv", "tartanair")
    hdr = ["# Training trends from policy snapshots (generated by scripts/snapshot_trends.py)\n",
           "Evaluation repeat 0 only (deterministic actions); multi-seed methods are averaged over seeds per snapshot. "
           "TUM ATE = mean over desk, desk2, plant, teddy, xyz (only meaningful while those are finished). "
           f"SVO rules (repeat 0): TUM ATE {rules['tum_ate']:.3f}, finished {rules['tum_fin']}/9, "
           f"failures {rules['tum_fails']:.0f}, kf {rules['tum_kf']:.2f}; TartanAir core finished "
           f"{rules_tar['tar_fin']}/6, failures/traj {rules_tar['tar_fails']:.2f}, kf {rules_tar['tar_kf']:.2f}.\n",
           "| Method | Seeds | Steps [k] | TUM ATE | TUM finished /9 | TUM failures | TUM kf rate | "
           "TartanAir finished /6 | TartanAir failures/traj | TartanAir kf rate |", "|---|---|---|---|---|---|---|---|---|---|"]
    f = lambda v, d: "-" if v != v else f"{v:.{d}f}"  # noqa: E731
    for _, r in t.iterrows():
        hdr.append(f"| {r.method} | {r.seeds} | {r['steps [k]']} | {f(r.tum_ate, 3)} | {f(r.tum_fin, 1)} | "
                   f"{f(r.tum_fails, 1)} | {f(r.tum_kf, 2)} | {f(r.tar_fin, 1)} | {f(r.tar_fails, 2)} | {f(r.tar_kf, 2)} |")
    out = ROOT / "results/tables/snapshot_trends.md"
    out.write_text("\n".join(hdr) + "\n")
    print("\n".join(hdr))

    panels = [("tum_ate", "TUM ATE [m] (5 common seqs)", rules["tum_ate"]),
              ("tum_kf", "TUM keyframe rate", rules["tum_kf"]),
              ("tum_fails", "TUM failures / run (9 seqs)", rules["tum_fails"]),
              ("tar_fails", "TartanAir failures / traj (core 6)", rules_tar["tar_fails"])]
    fig, axes = plt.subplots(1, 4, figsize=(20, 4.5))
    for ax, (k, title, ref) in zip(axes, panels):
        for label, df in curves.items():
            if k in df:
                ls = "--" if "7 scenes" in label else "-"
                ax.plot(df.steps / 1e3, df[k], ls, marker="o", ms=3, label=label)
        ax.axhline(ref, color="k", lw=1, ls=":", label="SVO rules")
        ax.set_title(title)
        ax.set_xlabel("training steps [k]")
        ax.set_xscale("log")
    axes[0].legend(fontsize=7)
    fig.tight_layout()
    fig.savefig(ROOT / "results/figures/snapshot_trends.png", dpi=130)


if __name__ == "__main__":
    main()
